In [1]:
from IPython.display import Markdown
import pandas as pd
from sentence_transformers import SentenceTransformer
from openai import OpenAI

from consultas_parte_1 import recuperar_top_k
from consultas_parte_2 import query_partido_tema, query_comparacion_partidos, contexto_filtro_edad
from funciones_generales import generar_respuesta_rag

from parametros import API_KEY

cliente = OpenAI(api_key=API_KEY)
modelo_e5 = SentenceTransformer('intfloat/multilingual-e5-base')

/home/jimenin/proyecto_millenniumdb/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10131.05it/s]

# Parte 1

In [ ]:
pregunta = "¿Qué argumentos surgieron sobre la reducción de la jornada laboral a 40 horas?"
df_recuperado = recuperar_top_k(
    pregunta_usuario=pregunta,
    modelo_e5=modelo_e5
)
df_recuperado

,texto_intervencion,contexto_intervencion,score_similitud
0,"Señor Presidente, saludo, como todos los han h...",plenary,0.130577
1,"Señorita Presidenta, lo primero que quiero dec...",plenary,0.131409
2,"Señorita Presidenta, este proyecto se ha dilat...",plenary,0.139593
3,"Señor Presidente, quiero saludar a la nueva mi...",plenary,0.139616
4,"Señor Presidente, antes de entrar al proyecto ...",plenary,0.139795
5,"Señora Presidenta, reducir la jornada laboral ...",plenary,0.140691
6,"Señor Presidente, saludo, como todos los han h...",plenary,0.141570
7,"Señor Presidente, durante el año pasado, tuve ...",plenary,0.142006
8,"Señor Presidente, este proyecto se sustenta en...",plenary,0.142146
9,"Señorita Presidenta, lo primero que quiero dec...",plenary,0.142155

In [ ]:
respuesta = generar_respuesta_rag(pregunta, df_recuperado, cliente)
display(Markdown(respuesta))

Los argumentos sobre la reducción de la jornada laboral a 40 horas en el debate legislativo chileno se pueden agrupar en dos posturas principales: a favor y en contra.

**Posturas a favor:**
1. **Mejora de la calidad de vida**: Se argumenta que la reducción de la jornada laboral es un acto de justicia que permitirá a los trabajadores tener más tiempo para la vida familiar y mejorar su salud mental. Se menciona que muchos trabajadores sufren problemas de salud mental debido a la excesiva carga laboral, y que un descanso adecuado es fundamental para la productividad ([1], [5], [7]).

2. **Demanda histórica**: La reducción de la jornada laboral a 40 horas se presenta como una materialización de una demanda histórica del movimiento obrero, que busca dignificar el trabajo y responder a las necesidades de los trabajadores. Se hace referencia a la consigna de "ocho horas para trabajar, ocho horas de descanso y ocho horas de recreación" como un principio fundamental de justicia social ([1], [6]).

3. **Apoyo ciudadano**: Se destaca que un alto porcentaje de la población (70%) apoya esta iniciativa, lo que refleja un consenso social sobre la necesidad de cambiar las condiciones laborales en el país ([0], [6]).

4. **Evidencia de productividad**: Se argumenta que jornadas laborales más cortas no afectan negativamente la productividad. Se citan ejemplos de mipymes que han implementado la jornada de 40 horas con éxito, demostrando que es posible mantener la productividad con menos horas de trabajo ([1], [9]).

5. **Flexibilidad y gradualidad**: Se menciona la importancia de permitir flexibilidad y gradualidad en la implementación de la reducción de la jornada, lo que podría ayudar a mitigar preocupaciones sobre la adaptación de las empresas a esta nueva normativa ([2], [3]).

**Posturas en contra:**
1. **Impacto en la productividad**: Se argumenta que la reducción de la jornada laboral podría llevar a una disminución de la productividad, ya que en muchos casos, la productividad está relacionada con la cantidad de horas trabajadas. Se menciona que en países donde se ha reducido la jornada, primero se incrementó la productividad antes de disminuir las horas trabajadas ([4], [8]).

2. **Costos para las empresas**: Se expresa preocupación por el aumento de costos que la reducción de la jornada podría implicar para las empresas, especialmente para las pequeñas y medianas. Se argumenta que esto podría llevar a un aumento en los precios de los productos y a la necesidad de contratar más personal, lo que podría resultar en un encarecimiento del trabajo y potencialmente en despidos ([4], [8]).

3. **Falta de evidencia sobre efectos positivos**: Algunos oradores cuestionan la falta de estudios que respalden la afirmación de que la reducción de la jornada no tendrá efectos negativos en salarios o empleos. Se argumenta que no se han presentado suficientes evidencias que demuestren que esta medida beneficiará a los trabajadores a largo plazo ([8], [9]).

4. **Exclusiones y limitaciones**: Se señala que el proyecto podría dejar fuera a ciertos sectores de trabajadores, lo que podría generar desigualdades en la aplicación de la nueva normativa. Se menciona la necesidad de incluir a todos los trabajadores, independientemente de su sector, para evitar crear un marco laboral desigual ([3], [4]).

En resumen, el debate sobre la reducción de la jornada laboral a 40 horas en Chile está marcado por una fuerte defensa de los derechos laborales y la calidad de vida de los trabajadores, frente a preocupaciones sobre la productividad y los costos económicos que esta medida podría acarrear.

In [ ]:
pregunta = "¿Cuáles fueron los principales argumentos a favor y en contra del aborto?"
df_recuperado = recuperar_top_k(
    pregunta_usuario=pregunta,
    modelo_e5=modelo_e5
)
respuesta = generar_respuesta_rag(pregunta, df_recuperado, cliente)
display(Markdown(respuesta))

Los principales argumentos en contra del aborto, según las intervenciones legislativas, se pueden agrupar de la siguiente manera:

1. **Derecho a la vida del no nacido**: Muchos oradores enfatizaron que el ser humano en gestación tiene derecho a la vida desde el momento de la concepción. Se argumentó que el aborto es una forma de asesinato y que el feto es un ser humano con dignidad y derechos inherentes, independientemente de su estado de salud o las circunstancias de su concepción ([0], [1], [2], [3], [4], [5], [6], [7], [8], [9]).

2. **Consecuencias psicológicas y físicas del aborto**: Se mencionó que muchas mujeres que abortan enfrentan traumas psicológicos y secuelas físicas. Se argumentó que, en lugar de promover el aborto, la sociedad debería ofrecer apoyo a las mujeres embarazadas y a las familias, enfatizando la importancia de acompañar a las mujeres en lugar de optar por la interrupción del embarazo ([2], [3], [6], [9]).

3. **Cuestionamiento de la autonomía de la mujer**: Algunos oradores argumentaron que la narrativa de que la mujer es dueña de su cuerpo ignora la existencia de un ser humano en desarrollo. Se planteó que esta visión puede llevar a la cosificación de la mujer y a una falta de consideración por la vida del feto, lo que contradice principios de justicia y solidaridad social ([1], [4], [6], [9]).

4. **Incoherencias en la legislación**: Se argumentó que la despenalización del aborto en ciertas causales podría abrir la puerta a un aborto más amplio y sin restricciones, lo que se consideró un peligro para la vida del no nacido. Se mencionó que el proyecto de ley podría ser un primer paso hacia el aborto libre, lo que generaría una mayor desprotección de los derechos del feto ([5], [6], [7], [9]).

5. **Dignidad humana y moralidad**: Se hizo hincapié en que la dignidad del ser humano debe ser protegida en todas las etapas de la vida, y que el aborto representa una violación a este principio. Se argumentó que la vida humana no puede ser instrumentalizada ni considerada como un medio para resolver problemas sociales o personales ([4], [8], [9]).

Por otro lado, los argumentos a favor del aborto, aunque menos explícitos en el contexto proporcionado, se pueden inferir de las críticas a la postura en contra:

1. **Autonomía de la mujer**: Se defendió la idea de que las mujeres deben tener el derecho a decidir sobre su propio cuerpo y sus vidas, lo que incluye la decisión de interrumpir un embarazo. Este argumento se basa en la noción de que el Estado no debe imponer obligaciones sobre decisiones tan personales ([1], [6]).

2. **Circunstancias excepcionales**: Se mencionaron situaciones extremas, como el riesgo para la vida de la madre o casos de violación, donde se argumenta que el aborto podría ser una opción necesaria. Sin embargo, los oradores en contra del aborto cuestionaron la validez de estas causales y su aplicación práctica ([3], [8]).

En resumen, el debate se centró en la defensa del derecho a la vida del no nacido frente a la autonomía de la mujer, con un fuerte énfasis en la dignidad humana y las implicaciones morales del aborto.

In [18]:
pregunta = "¿Qué dicen los políticos respecto a las energías renovables en Chile?"
df_recuperado = recuperar_top_k(
    pregunta_usuario=pregunta,
    modelo_e5=modelo_e5
)
respuesta = generar_respuesta_rag(pregunta, df_recuperado, cliente)
display(Markdown(respuesta))

Los políticos en Chile expresan una variedad de posturas respecto a las energías renovables, destacando tanto su potencial como los desafíos que enfrentan en su implementación y desarrollo.

1. **Potencial de las energías renovables**: Muchos oradores resaltan la capacidad de Chile para convertirse en un líder en la producción de energías limpias, especialmente en energías renovables no convencionales como la solar y el hidrógeno verde. Se menciona que Chile tiene un gran potencial para producir energía limpia y que el hidrógeno verde podría posicionar al país como uno de los principales productores a nivel mundial ([1], [2]). Además, se hace hincapié en la necesidad de diversificar la matriz energética y reemplazar fuentes contaminantes como las termoeléctricas a carbón por energías más limpias y sostenibles ([4], [5]).

2. **Críticas a la burocracia y a la falta de políticas efectivas**: Algunos políticos critican la falta de una política energética de Estado que permita un desarrollo ágil de proyectos de energías renovables. Se menciona que la burocracia y la falta de coordinación en los permisos necesarios dificultan la implementación de estos proyectos, lo que retrasa la transición hacia una matriz energética más limpia ([2], [3], [6]). También se señala que, a pesar de los avances, muchas comunidades no se benefician de estos desarrollos, lo que genera un descontento en regiones productoras de energía como el Maule ([8]).

3. **Impacto en comunidades locales**: Hay una preocupación por el impacto que los proyectos de energías renovables pueden tener en las comunidades locales, especialmente en aquellas que ya son consideradas "zonas de sacrificio". Se argumenta que, aunque se busca avanzar hacia energías más limpias, esto no debe hacerse a expensas de la calidad de vida de las personas que viven en estas áreas ([3], [7], [8]). Algunos oradores expresan que la transición energética debe ser justa y considerar las necesidades de las comunidades afectadas.

4. **Responsabilidad en la transición**: Existe un consenso sobre la necesidad de cerrar las termoeléctricas de manera responsable, asegurando que haya suficiente infraestructura de transmisión y alternativas energéticas disponibles para evitar problemas como el racionamiento energético o el aumento de costos para los ciudadanos ([4], [5]). Se enfatiza que la transición hacia energías renovables debe ser planificada y ejecutada con cuidado para no perjudicar a la población.

5. **Educación y concienciación**: Algunos políticos abogan por la necesidad de educar a la ciudadanía sobre el consumo responsable de energía y la importancia de la transición hacia energías renovables, sugiriendo que una mejor comprensión de estos temas puede ayudar a mitigar la resistencia a los proyectos energéticos ([2], [6]).

En resumen, los políticos chilenos reconocen el potencial de las energías renovables y la necesidad de avanzar hacia una matriz energética más limpia, pero también expresan preocupaciones sobre la implementación, el impacto en las comunidades locales y la necesidad de una transición responsable y justa.

# Parte 2

## Recuperación con restricción tipada

In [39]:
tema_a_buscar = "legalización del aborto"
partido_objetivo = "Partido Humanista"
df_recuperado = query_partido_tema(partido_objetivo, tema_a_buscar, modelo_e5)
df_recuperado

,texto_intervencion,contexto_intervencion,partido_politico,score_similitud
0,"Señor Presidente, las políticas públicas de vi...",plenary,Partido Humanista,0.184173
1,"Señor Presidente, hace unos días nos horrorizá...",plenary,Partido Humanista,0.191061
2,"Señor Presidente, este proyecto es transversal...",plenary,Partido Humanista,0.191194
3,"Señor Presidente, el gobierno ha cumplido con ...",plenary,Partido Humanista,0.193775
4,"Señor Presidente, el solo hecho de tener que c...",plenary,Partido Humanista,0.196267
5,"Señor Presidente, hace unos días nos horrorizá...",plenary,Partido Humanista,0.197128
6,"Señorita Presidenta, en esta Sala hay niños, n...",plenary,Partido Humanista,0.197503
7,"Señor Presidente, además, el informe señala qu...",plenary,Partido Humanista,0.197842
8,"Señor Presidente, en esta última sesión de la ...",plenary,Partido Humanista,0.199490
9,"Señor Presidente, las políticas públicas de vi...",plenary,Partido Humanista,0.202002

In [41]:
pregunta_llm = f"¿Qué opinan los políticos respecto a la {tema_a_buscar}?"
respuesta = generar_respuesta_rag(pregunta_llm, df_recuperado, cliente)
display(Markdown(respuesta))

El contexto recuperado no contiene información suficiente para responder a esta pregunta.

## Agregación / contraste

Para que el llm entregue una respuesta se necesitan más documentos

In [35]:
tema_a_buscar = "reducción de la jornada laboral a 40 horas semanales"
df_recuperado = query_comparacion_partidos(tema_a_buscar, modelo_e5)
df_recuperado

,Partido,Texto,Contexto,score_similitud
0,Partido Demócrata Cristiano,"La señora PROVOSTE.- Muchas gracias, President...",plenary,0.160748
1,Partido Socialista de Chile,"La señora VODANOVIC.- Gracias, Presidente.<br/...",plenary,0.162651
2,Partido Republicano de Chile,"Señor Presidente, como lo he dicho en otros pr...",plenary,0.165574
3,Partido Republicano de Chile,"Señor Presidente, en primer lugar, quiero feli...",plenary,0.166613
4,Partido Demócrata Cristiano,"Señor Presidente, el voto obligatorio le hace ...",plenary,0.169372
5,Partido Evolución Política (Evópoli),"Señor Presidente, quiero señalar varias cosas ...",plenary,0.169415
6,Partido Humanista,"Señor Presidente, el gobierno ha cumplido con ...",plenary,0.169676
7,Partido Demócrata Cristiano,"El señor WALKER.- Presidente, yo quiero apoyar...",plenary,0.171398
8,Partido Comunista de Chile,"Señor Presidente, en mi calidad de diputado in...",plenary,0.171797
9,Partido Unión Demócrata Independiente,"Señor Presidente, yo, al igual que muchos de q...",plenary,0.171813

In [36]:
pregunta_llm = f"Contrasta las posturas de los distintos partidos políticos respecto a la {tema_a_buscar}. ¿En qué puntos coinciden y cuáles son sus principales diferencias?"
respuesta = generar_respuesta_rag(pregunta_llm, df_recuperado, cliente)
display(Markdown(respuesta))

En el contexto de las intervenciones legislativas, se pueden identificar diversas posturas de los partidos políticos respecto a la reducción de la jornada laboral a 40 horas semanales, aunque no todos los partidos abordan este tema de manera directa.

1. **Partido Demócrata Cristiano (PDC)**: La senadora Provoste menciona que la regulación de la jornada de descanso de los conductores interurbanos se aplicará gradualmente de acuerdo a la ley de las 40 horas. Esto sugiere un apoyo a la reducción de la jornada laboral, pero también expresa preocupación por la inclusión de este tema en un proyecto de ley misceláneo que abarca diversas materias, lo que podría dificultar un análisis adecuado por parte de las comisiones especializadas ([0]).

2. **Partido Socialista (PS)**: Aunque no se menciona directamente la reducción de la jornada laboral a 40 horas, la senadora Vodanovic se enfoca en la importancia de los derechos laborales y la necesidad de proteger a los trabajadores, lo que puede implicar un apoyo implícito a la reducción de la jornada laboral como parte de un marco más amplio de derechos laborales ([1]).

3. **Partido Republicano (PR)**: Este partido no aborda directamente la reducción de la jornada laboral, pero critica la falta de sentido común en la tramitación de proyectos que consideran irrelevantes en el contexto de problemas más urgentes, como la seguridad y la economía. Esto sugiere que podrían ver la reducción de la jornada laboral como un tema secundario frente a otros problemas más apremiantes ([2]).

4. **Partido Evolución Política (Evópoli)**: Aunque no se menciona la reducción de la jornada laboral, el diputado Undurraga expresa preocupaciones sobre la implementación de políticas laborales sin el respaldo de los ministerios correspondientes, lo que podría implicar una crítica a la falta de un enfoque integral en la legislación laboral, incluyendo la jornada laboral ([5]).

5. **Partido Humanista (PH)**: Este partido se enfoca en la necesidad de un sueldo vital y en mejorar las condiciones laborales de los trabajadores, lo que puede estar alineado con la idea de reducir la jornada laboral a 40 horas como parte de un enfoque más amplio hacia la dignidad laboral y el bienestar de los trabajadores ([6]).

**Coincidencias**:
- Hay un reconocimiento general de la importancia de mejorar las condiciones laborales y de proteger los derechos de los trabajadores, lo que puede incluir la reducción de la jornada laboral.
- La preocupación por la implementación de cambios laborales sin un análisis adecuado y el respaldo de las instituciones pertinentes es un punto común entre varios partidos.

**Diferencias**:
- El PDC muestra un apoyo más explícito a la reducción de la jornada laboral, aunque con reservas sobre su inclusión en proyectos misceláneos, mientras que otros partidos como el PR no abordan el tema directamente y lo consideran menos prioritario.
- La falta de un enfoque claro y unificado sobre la reducción de la jornada laboral entre los partidos sugiere que no todos ven este cambio como una urgencia, lo que puede reflejar diferencias ideológicas y estratégicas en la agenda legislativa.

En resumen, aunque hay un consenso sobre la necesidad de mejorar las condiciones laborales, las posturas varían en cuanto a la urgencia y la forma de abordar la reducción de la jornada laboral a 40 horas semanales.

## Una consulta que use un atributo numérico/temporal

In [3]:
tema_a_buscar = "reducción de la jornada laboral a 40 horas semanales"
edad_objetivo = 40
df_recuperado = contexto_filtro_edad(tema_a_buscar, edad_objetivo, ">=", modelo_e5)
df_recuperado

,nombre,texto,score_similitud,edad_al_momento
0,Yasna Provoste Campillay,"La señora PROVOSTE.- Muchas gracias, President...",0.160748,55
1,Bernardo José Berger Fett,"Señorita Presidenta, honorable Cámara, hubiese...",0.163490,78
2,Ana María Gazmuri Vieira,"Señor Presidente, quiero partir mi intervenció...",0.163799,59
4,Javiera Ignacia Morales Alvarado,"Señor Presidente, en esta discusión he escucha...",0.167855,41
5,Mónica Tamara Arce Castro,"Señor Presidente, honorable Cámara, en nombre ...",0.168860,40
6,Alberto Undurraga Vicuña,"Señor Presidente, el voto obligatorio le hace ...",0.169372,56
7,Francisco Undurraga Gazitúa,"Señor Presidente, quiero señalar varias cosas ...",0.169415,60
8,Tomás Hirsch Goldschmidt,"Señor Presidente, el gobierno ha cumplido con ...",0.169676,68
10,Clara Inés Sagardia Cabezas,"Señor Presidente, no podemos proteger el medio...",0.171219,73
12,Luis Alberto Cuello Peña y Lillo,"Señor Presidente, en mi calidad de diputado in...",0.171797,48

In [43]:
pregunta_llm = f"¿Cuál es la postura de los políticos mayores de {edad_objetivo} años respecto a la {tema_a_buscar}?"
respuesta = generar_respuesta_rag(pregunta_llm, df_recuperado, cliente)
display(Markdown(respuesta))

La postura de los políticos mayores de 40 años respecto a la reducción de la jornada laboral a 40 horas semanales se manifiesta en un contexto de apoyo a la medida, aunque con matices y preocupaciones sobre su implementación y efectos.

Por un lado, se observa un respaldo a la idea de flexibilizar las jornadas laborales, especialmente en el caso de los conductores interurbanos, en el marco de la ley de las 40 horas. Yasna Provoste, por ejemplo, menciona que es urgente pronunciarse a favor de flexibilizar las jornadas laborales para los conductores, alineándose con el sentido de la ley de las 40 horas ([0]). Esto sugiere que hay un reconocimiento de la necesidad de adaptar las normativas laborales a las realidades del trabajo actual.

Sin embargo, también hay preocupaciones sobre la forma en que se están presentando estas iniciativas. Provoste advierte sobre los riesgos de las leyes misceláneas que incluyen temas diversos, lo que podría dificultar un diálogo más amplio y técnico sobre cuestiones sensibles como la reducción de la jornada laboral ([0]). Esto indica que, aunque hay apoyo a la reducción de la jornada, existe una necesidad de un debate más profundo y especializado sobre su implementación.

En resumen, los políticos mayores de 40 años parecen estar a favor de la reducción de la jornada laboral a 40 horas semanales, pero enfatizan la importancia de un análisis cuidadoso y un diálogo más amplio sobre las implicaciones de esta medida en el contexto de otras reformas laborales y normativas.

In [4]:
tema_a_buscar = "reducción de la jornada laboral a 40 horas semanales"
edad_objetivo = 40
df_recuperado = contexto_filtro_edad(tema_a_buscar, edad_objetivo, "<", modelo_e5)
df_recuperado

,nombre,texto,score_similitud,edad_al_momento
3,Cristián Andrés Araya Lerdo de Tejada,"Señor Presidente, como lo he dicho en otros pr...",0.165574,36
9,Andrés Sergio Giordano Salazar,"Señor Presidente, primero, saludo al Ejecutivo...",0.170419,38
11,Camila Ruzlay Rojas Valderrama,"Señor Presidente, me referiré a la indicación ...",0.171355,34
19,Andrés Sergio Giordano Salazar,"Señora Presidenta, quiero partir mi intervenci...",0.174076,38
21,Daniella Valentina Cicardini Milla,"Corresponde tratar el proyecto de ley, en prim...",0.174192,38
23,Diego Eduardo Ibáñez Cotroneo,"Señor Presidente, venimos tramitando este proy...",0.174304,36
31,Daniela Andrea Serrano Salazar,"Señorita Presidenta, el desempleo y la precari...",0.175034,30
32,Cristián Andrés Araya Lerdo de Tejada,"Señor Presidente, en el N° 13 de la Cuenta se ...",0.175400,36
36,Camila Ruzlay Rojas Valderrama,"Señor Presidente, el salario no es un premio: ...",0.175711,34
37,Andrés Sergio Giordano Salazar,"Señor Presidente, diputadas y diputados, quier...",0.175759,39

In [5]:
pregunta_llm = f"¿Cuál es la postura de los políticos menores de {edad_objetivo} años respecto a la {tema_a_buscar}?"
respuesta = generar_respuesta_rag(pregunta_llm, df_recuperado, cliente)
display(Markdown(respuesta))

La postura de los políticos menores de 40 años respecto a la reducción de la jornada laboral a 40 horas semanales se manifiesta principalmente a través de la defensa de esta medida como un avance significativo en la mejora de las condiciones laborales y la calidad de vida de los trabajadores.

Andrés Sergio Giordano Salazar, quien tiene 38 años, argumenta que la reducción de la jornada laboral es parte de un conjunto de reformas que buscan mejorar la calidad del trabajo y redistribuir la riqueza. Resalta que, aunque se ha mencionado que el aumento de costos laborales podría afectar el mercado del trabajo, las autoridades, incluido el Banco Central, han indicado que el impacto de las reformas laborales es acotado y que estas están en fase de implementación ([9]). Además, Giordano enfatiza que la reducción de la jornada laboral y el aumento del salario mínimo fueron aprobados de manera transversal, lo que indica un consenso sobre su importancia ([9]).

Por otro lado, Camila Ruzlay Rojas Valderrama, también de 34 años, defiende el aumento del salario mínimo en el contexto de la reducción de la jornada laboral, argumentando que estas medidas son parte de un esfuerzo por mejorar el poder adquisitivo de las familias y que el aumento del salario mínimo ha sido sostenido y no solo una respuesta electoral ([36]).

En resumen, los políticos menores de 40 años parecen estar a favor de la reducción de la jornada laboral a 40 horas semanales, viéndola como una medida necesaria para mejorar las condiciones laborales y la calidad de vida de los trabajadores, y apoyan la idea de que estas reformas son parte de un cambio más amplio hacia una mayor equidad y justicia social en el ámbito laboral ([9], [36]).

# Comparación RAG vs GraphRAG

In [6]:
pregunta = "¿Cuáles son los principales puntos que hacen los políticos jóvenes vs los políticos mayores respecto los precios de las viviendas?"
df_recuperado = recuperar_top_k(
    pregunta_usuario=pregunta,
    modelo_e5=modelo_e5
)
respuesta = generar_respuesta_rag(pregunta, df_recuperado, cliente)
display(Markdown(respuesta))

En el contexto de las intervenciones legislativas, se pueden identificar varias posturas y argumentos en relación con los precios de las viviendas, especialmente en la comparación entre políticos jóvenes y mayores.

1. **Dificultades para los jóvenes**: Los políticos jóvenes, como el senador Juan Castro, enfatizan que los matrimonios jóvenes enfrentan serias dificultades para adquirir una vivienda debido a los altos precios y a la forma en que se estructuran los pagos, que se realizan en unidades de fomento (UF) mientras que los sueldos son en pesos. Castro argumenta que esta situación crea una desigualdad significativa, ya que los sueldos no aumentan al mismo ritmo que la UF, lo que hace que la compra de vivienda sea prácticamente imposible para los jóvenes ([1], [9]).

2. **Necesidad de políticas públicas**: Los políticos jóvenes abogan por la necesidad de que el Estado implemente nuevas políticas públicas que faciliten el acceso a la vivienda. Castro, por ejemplo, propone que los dividendos se paguen en pesos y que se busquen fórmulas que permitan a los jóvenes endeudarse de manera justa y razonable para adquirir una vivienda ([1], [9]). Este enfoque se centra en la urgencia de abordar el déficit habitacional y las condiciones económicas que enfrentan los jóvenes.

3. **Visión de los políticos mayores**: Por otro lado, algunos políticos mayores, como el diputado que critica el proyecto de ley propuesto por la diputada Karol Cariola, argumentan que las restricciones a la capacidad de los ciudadanos para hipotecar sus viviendas sociales limitan su libertad de decisión. Este político sostiene que las personas deben tener la libertad de decidir cómo manejar su propiedad, incluso si eso implica ponerla en garantía para acceder a créditos ([8]). Esta postura refleja una preocupación por la autonomía individual y la capacidad de los ciudadanos para tomar decisiones informadas sobre su situación financiera.

4. **Enfoque en la protección social**: Los políticos mayores también tienden a enfatizar la importancia de proteger a los adultos mayores y a las familias vulnerables en el contexto de la vivienda. Se argumenta que las políticas deben considerar las diferentes etapas de la vida y las necesidades específicas de cada grupo, como los adultos mayores que pueden estar en riesgo de perder su vivienda ([4], [2]).

5. **Crítica a la especulación inmobiliaria**: Algunos políticos jóvenes critican la mercantilización de la vivienda y la especulación inmobiliaria, argumentando que esto ha convertido la vivienda en un bien de inversión en lugar de un derecho. Este enfoque busca abordar las raíces del problema de acceso a la vivienda, más allá de las soluciones inmediatas que se puedan proponer ([6]).

En resumen, los políticos jóvenes tienden a centrarse en la necesidad de políticas que faciliten el acceso a la vivienda para los jóvenes, mientras que los políticos mayores pueden enfocarse más en la protección de los derechos de los ciudadanos y la libertad de decisión en el manejo de sus propiedades. Ambos grupos reconocen la complejidad del problema, pero sus enfoques y prioridades pueden diferir significativamente.

In [6]:
tema_a_buscar = "precios de las viviendas"
df_recuperado_menos50 = contexto_filtro_edad(tema_a_buscar, 50, "<", modelo_e5)
df_recuperado_mas50 = contexto_filtro_edad(tema_a_buscar, 50, ">=", modelo_e5)

df_recuperado = pd.concat([df_recuperado_menos50.iloc[:5], df_recuperado_mas50.iloc[:5]])
df_recuperado = df_recuperado.sort_values(by="score_similitud").reset_index(drop=True)
df_recuperado

,nombre,texto,score_similitud,edad_al_momento
0,Carlos Ignacio Kuschel Silva,"El señor KUSCHEL.- Gracias, señor Presidente.<...",0.148275,72
1,Miguel Mellado Suazo,"Señor Presidente, el gobierno presentó un proy...",0.148379,66
2,Héctor David Ulloa Aguilera,"Señor Presidente, ¿cuántas veces hemos escucha...",0.148486,55
3,Carlos Antonio Karim Bianchi Chelech,"Señor Presidente, este proyecto no es un león ...",0.150247,64
4,David Sandoval Plaza,"<br/>El señor SANDOVAL.- Muchas gracias, Presi...",0.150270,72
5,José Carlos Meza Pereira,"Señor Presidente, la verdad es que se pueden d...",0.151496,36
6,Juan Ignacio Latorre Riveros,"El señor LATORRE.- Gracias, Presidente.<br/>Pr...",0.153597,47
7,Andrés Sergio Giordano Salazar,"Señor Presidente, hoy quiero hablarles a quien...",0.154674,38
8,Matías Felipe Ramírez Pascal,"Señor Presidente, estamos discutiendo un proye...",0.158946,40
9,Héctor Alejandro Barría Angulo,"Señor Presidente, este es un proyecto muy impo...",0.159159,45

In [ ]:
pregunta_llm = "¿Cuáles son los principales puntos que hacen los políticos jóvenes vs los políticos mayores respecto los precios de las viviendas?"
respuesta = generar_respuesta_rag(pregunta_llm, df_recuperado, cliente)
display(Markdown(respuesta))

En el debate legislativo sobre el acceso a la vivienda y los precios de las viviendas, se pueden identificar diferencias significativas entre las posturas de los políticos jóvenes y los mayores.

**Posturas de los políticos jóvenes:**
1. **Enfoque en la clase media y la necesidad de intervención estatal:** Los políticos jóvenes, como Juan Ignacio Latorre y Andrés Giordano, enfatizan la importancia de que el Estado intervenga para facilitar el acceso a la vivienda, especialmente para la clase media. Latorre menciona que el proyecto busca contribuir a que las personas de clase media accedan a una vivienda mediante subsidios a la tasa de interés de los créditos hipotecarios ([6]). Giordano también destaca que el acceso a la vivienda se ha vuelto cada vez más difícil debido a las condiciones del mercado, y que la especulación inmobiliaria ha convertido la vivienda en un bien de inversión en lugar de un derecho ([7]).

2. **Crítica a la mercantilización de la vivienda:** Los jóvenes critican la mercantilización del derecho a habitar y abogan por una política habitacional integral que no solo se enfoque en viviendas nuevas, sino que también considere la adquisición de viviendas usadas ([8]). Esto refleja una preocupación por la diversidad de necesidades habitacionales en el país.

3. **Llamado a la descentralización y políticas diferenciadas:** Algunos políticos jóvenes, como Matías Ramírez, abogan por políticas que reconozcan las particularidades económicas y sociales de cada región, sugiriendo que el Estado debería participar más activamente en el mercado inmobiliario para regular precios y garantizar el acceso a la vivienda ([8]).

**Posturas de los políticos mayores:**
1. **Enfoque en la reactivación económica:** Los políticos mayores, como Miguel Mellado y Carlos Kuschel, tienden a centrarse en la necesidad de reactivar la economía a través de la construcción y venta de viviendas. Mellado critica que el proyecto se ha limitado a personas naturales y ha excluido a las personas jurídicas, lo que, según él, ha afectado negativamente la reactivación del sector de la construcción ([1]). Kuschel también menciona que las decisiones legislativas han encarecido las condiciones de oferta y demanda en la construcción y compra de viviendas ([0]).

2. **Preocupación por el aumento de costos:** Los políticos mayores expresan una preocupación significativa por el aumento de los costos de construcción y de las viviendas. Mellado menciona que los costos de los materiales de construcción han aumentado un 60% en los últimos cinco años, lo que ha llevado a un "sobrestock" de viviendas ([1]). Esta preocupación se refleja en la necesidad de encontrar soluciones que permitan a las familias acceder a viviendas a precios razonables.

3. **Visión crítica sobre la efectividad de las políticas actuales:** Algunos políticos mayores, como José Carlos Meza, critican la efectividad de las políticas de vivienda del gobierno actual, argumentando que no se están cumpliendo las expectativas y que se necesita una mayor agilidad en la política de vivienda ([5]).

En resumen, los políticos jóvenes tienden a enfocarse en la necesidad de intervención estatal y en la crítica a la mercantilización de la vivienda, mientras que los políticos mayores se centran más en la reactivación económica y en la preocupación por el aumento de costos en el sector de la vivienda.

Solo usar RAG provoca que el llm tenga inferir la edad de los políticos en base al contexto, lo que hace que ser jóven quede a criterio del llm. Un ejemplo de esto es el senador Juan Castro que el llm lo cataloga de político joven, siendo que en la actualidad tiene 66 años dificilmente pudiendo catalogarse como jóven al lado de políticos de menos de 40. Por lo mismo, no queda claro si la visión entregada es realmente la de políticos jóvenes o no. 

En cambio, el uso de GraphRAG le permitió al llm discernir las posturas entre grupos etarios claramente, gracias a que ahora está a dispocision la edad al momento de la intervención. Las respuestas dadas entregan una visión clara de ambos grupos etarios sin la incertidumbre del caso anterior.